language: node_js
os: windows
addons:
  apt:
    packages:
      # needed by Cypress, not in Ubuntu 16+ by default
      - libgconf-2-4
script:
  - cypress run --key 01beea46-5bc0-41a9-be9d-03eedaf36589
